kumuluzee:
  name: rso-items
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ItemsDS
      connection-url: jdbc:postgresql://172.17.0.1:5432/items
      username: dbuser
      password: postgres
      max-pool-size: 20
